import assert from 'node:assert/strict'; import fs from 'node:fs'; import os from 'node:os'; import path from 'node:path';
import { createMonitorWorker, openMonitorStore, canonicalBarKey, identityKey } from './src/monitor/index.js';
const id = { provider: 'tv', exchange: 'HOSE', symbol: 'AAA', full_symbol: 'HOSE:AAA', timeframe: '60', pane: 'p', layout: 'l', profile: 'vn-stock.v1' }; let calls = [];
const reader = { readIdentity: async () => { calls.push('identity'); return id; }, readSnapshot: async () => ({ identity: id, timeframe: '60', bar_open_timestamp: 1_700_000_000_000, bar_index: 1, source_timestamp: 1_700_000_000_000, receipt_timestamp: 1_700_000_000_000, evaluated_at: 1_700_000_000_000, bar_closed: false, evidence: [] }) };
const w = createMonitorWorker({ watchlist: [{ ...id, asset_class: 'VN_STOCK', tier: 'CORE' }], reader, store: openMonitorStore({ rootDir: fs.mkdtempSync(path.join(os.tmpdir(), 'monitor-w-')) }), clock: () => 1_700_000_000_000 }); await w.runOnce(); assert.deepEqual(calls, ['identity']); w.stop(); console.log('ALL PASS');

const root = fs.mkdtempSync(path.join(os.tmpdir(), 'monitor-w-confirm-')); const store = openMonitorStore({ rootDir: root }); const bar = canonicalBarKey({ identity: id, timeframe: '60', session: 'CONT_AM', bar_open_timestamp: 1_700_000_000_000, bar_index: 1 });
const evidence = [{ family: 'levels', source_id: 'l', bar_key: bar, config_version: 'cfg.v1', policy_version: 'policy.v1', profile: id.profile, session: 'CONT_AM', freshness: 'FRESH', canonical_value: 1, direction: 'BULLISH' }, { family: 'structure', source_id: 's', bar_key: bar, config_version: 'cfg.v1', policy_version: 'policy.v1', profile: id.profile, session: 'CONT_AM', freshness: 'FRESH', canonical_value: 2, direction: 'BULLISH' }]; let n = 0;
const snapshots = [false, true, true].map((closed, i) => ({ identity: id, timeframe: '60', session: 'CONT_AM', bar_open_timestamp: 1_700_000_000_000, bar_index: 1, source_timestamp: 1_700_000_000_000, receipt_timestamp: 1_700_000_000_000 + i, evaluated_at: 1_700_000_000_000 + i, bar_closed: closed, evidence }));
const confirmReader = { readIdentity: async () => id, readSnapshot: async () => snapshots[n++] }; const item = { ...id, asset_class: 'VN_STOCK', tier: 'CORE', sessionPolicy: { version: 'policy.v1', sessions: ['CONT_AM'] } }; const engineNow = 1_700_000_005_000; const cw = createMonitorWorker({ watchlist: [item], reader: confirmReader, store, clock: () => engineNow }); await cw.runOnce(); await cw.runOnce(); await cw.runOnce(); assert.equal(cw.states.get(identityKey(id)).state.status, 'CONFIRMED'); const replay = store.replay(); assert.ok(replay.events.at(-1).identity_key && replay.events.at(-1).evidence_revision !== undefined); assert.notEqual(replay.checkpoints.at(-1).last_seen, snapshots[2].evaluated_at); const rw = createMonitorWorker({ watchlist: [item], reader: confirmReader, store, clock: () => engineNow }); assert.equal(rw.states.size, 1); assert.equal(rw.states.get(identityKey(id)).state.last_seen, replay.checkpoints.at(-1).last_seen); console.log('ALL PASS');

const barA = canonicalBarKey({ identity: id, timeframe: '60', session: 'CONT_AM', bar_open_timestamp: 1_700_000_000_000, bar_index: 1 }); const barB = canonicalBarKey({ identity: id, timeframe: '60', session: 'CONT_AM', bar_open_timestamp: 1_700_003_600_000, bar_index: 2 }); const evB = evidence.map(e => ({ ...e, bar_key: barB })); let m = 0; const seq = [{ ...snapshots[0], evidence: evidence.map(e => ({ ...e, bar_key: barA })) }, { ...snapshots[1], bar_open_timestamp: 1_700_003_600_000, bar_index: 2, bar_closed: true, evidence: evB }, { ...snapshots[2], bar_open_timestamp: 1_700_003_600_000, bar_index: 2, bar_closed: true, receipt_timestamp: 1_700_000_000_002, evaluated_at: 1_700_000_000_002, evidence: evB }]; const bw = createMonitorWorker({ watchlist: [item], reader: { readIdentity: async () => id, readSnapshot: async () => seq[m++] }, store: openMonitorStore({ rootDir: fs.mkdtempSync(path.join(os.tmpdir(), 'monitor-w-bars-')) }), clock: () => 1_700_000_000_000 }); await bw.runOnce(); const aCandidate = bw.states.get(identityKey(id)).state.candidate_id; await bw.runOnce(); const bCandidate = bw.states.get(identityKey(id)).state.candidate_id; assert.notEqual(aCandidate, bCandidate); await bw.runOnce(); assert.equal(bw.states.get(identityKey(id)).state.status, 'CONFIRMED');
